GET http://localhost:8000

###

POST  http://localhost:8000/register
Content-Type: application/json

{
  "userName": "hinata",
  "email": "hinata@example.com",
  "password": "@Hello123",
  "confirmPassword": "@Hello123"
}

###

POST  http://localhost:8000/login
Content-Type: application/json

{
  "userName": "hinata2",
  "password": "@Hello123"
}

###

GET http://localhost:8000/650a00869cd588867ff07fb9

###

PUT http://localhost:8000/650c2a47345502e8bdc2ca89
Content-Type: application/json

{
  "userName": "blue",
  "email": "blue@example.com"
}





